safe: true
lsi: false
future: true
#hightlighter: pygments
permalink: /:year/:month/:day/:title.html
paginate: 10
#markdown: kramdown
kramdown:
    input: GFM
excerpt_separator: <!--more-->
plugins: 
    - jekyll-paginate

